[package]
name = "alloy-signer-aws"
version = "1.0.41"
edition = "2021"
rust-version = "1.86"
authors = ["Alloy Contributors"]
description = "Ethereum AWS KMS signer"
homepage = "https://github.com/alloy-rs/alloy"
repository = "https://github.com/alloy-rs/alloy"
license = "MIT OR Apache-2.0"
readme = "README.md"

[lib]
name = "alloy_signer_aws"
path = "src/lib.rs"

[features]
eip712 = ["alloy-signer/eip712"]

[dependencies]
alloy-consensus = { version = "1.0.41", features = ["std"], default-features = false }
alloy-network = { version = "1.0.41", default-features = false }
alloy-primitives = { version = "1.2.0", default-features = false }
alloy-signer = { version = "1.0.41", default-features = false }
async-trait = "0.1"
aws-config = { version = "1", default-features = false }
aws-sdk-kms = { version = "1", default-features = false }
k256 = { version = "0.13", features = ["ecdsa"], default-features = false }
spki = { version = "0.7", features = ["std"], default-features = false }
thiserror = { version = "2.0", default-features = false }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
