name: Run Program

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run_program:
    name: Test SP1 Helios Program
    runs-on: [runs-on, runner=4cpu-linux-arm64	, "run-id=${{ github.run_id }}"]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install SP1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          ~/.sp1/bin/sp1up 
          ~/.sp1/bin/cargo-prove prove --version
          source ~/.bashrc
      - name: Run test
        run: |
          cd script
          cargo run --bin test
        env:
          SOURCE_CONSENSUS_RPC_URL: ${{ secrets.SOURCE_CONSENSUS_RPC_URL }}
          SOURCE_CHAIN_ID: ${{ secrets.SOURCE_CHAIN_ID }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DEST_RPC_URL: ${{ secrets.DEST_RPC_URL }}
          DEST_CHAIN_ID: ${{ secrets.DEST_CHAIN_ID }}
